### ISSUE TITLE
Graduate Student Showcase 11/12 poster presentation

### ISSUE THREAD

**Issue by wendtke** [psyphr-dev/writing#1]
The Grad School Dean helped support my travel to the Uncoast Unconf and requested that I share our resulting work in the [Grad Student Showcase](https://wsnet2.colostate.edu/cwis478/GraduateStudentShowcase/).

**Possible poster sections/topics**

- Introduction: Establish need for `psyphr` (e.g., problems existing research practices; sheer quantity of data; number of labs/users)
- Open science movement and reproducibility
- Unconference: What is it? What did we do there? Why are they useful?
- `psyphr.read`: show functions via vignettes and example data

**Comment by wendtke** [comment]
@MalloryJfeldman 

Are you able to help me with content for the introduction/statement of the problem? See gss_poster/R/poster_content.Rmd(pdf). You can create a branch, add stuff to Rmd, and create PR.

**Comment by MalloryJfeldman** [comment]
@wendtke I added some bullets under the intro. Feel free to keep or omit!

**Comment by MalloryJfeldman** [comment]
Brain-dump - main issues. 

- Currently, to collect and clean physiology data you need multiple software which are versioned and expensive (this is a gateway)
- Typically, with psychophysiological research software produces several output files per-person (e.g., across signals or tasks)
- Storing, compiling, and wrangling this data introduces several challenges which introduce several researcher degrees of freedom, and opportunities for error (e.g., copying and pasting errors). 
- Additionally, physiological data must often be aligned with psychological data making successful data wrangling an even greater imperative. 
- Because there is no standardized pipeline, data formatting is not equipped to be shared (internally or externally)
- In general, external efforts to establish naming and formatting guidelines for psychological data have not been successfully extended to physiological data (e.g., BIDS) 
- Thus successfully collecting, cleaning, formatting, analyzing, visualizing, and sharing of psychophysiological data is critical if we are to increase the efficacy, transparency, quality, and reproducibility of our research (and decrease the researcher hours and errors caused by current processing pipelines which use some combination of proprietary software, excel, and programming languages such as R)

**Comment by wendtke** [comment]
Any ideas for viz? How to show current workflow problems?

**Comment by wendtke** [comment]
GBA suggestions and other things @iqis @MalloryJfeldman
- [x] Number sections for easy eye-tracking left-to-right
- [x] Visual of psyphr as umbrella package: psyphr.read in bold/others faded to show what we have done and will do (either in intro or future directions)
- [x] **With one line of code**... all of these files are wrangled and tidy!
- [ ] Show ease of tidy df into summary statistics or plot
- [ ] License Caroline's hex sticker under Creative Commons [license](https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license)
- [x] check print details and requirements
- [ ] where to put poster after presentation (BSB or ERHS?) 
- [ ] can create screen cast with embedded descriptions (old process vs. psyphr) to show during presentation(s) and include in tutorials
- [x] include “This material is based upon work supported by the National Science Foundation Graduate Research Fellowship under Grant No. 006784-00002.”
- [x] double-check [NSF](https://www.nsf.gov/policies/logos.jsp) logo use requirements
